### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by alexlfyang** [kaituoxu/SpeechTransformer#28]
```
Traceback (most recent call last):
    File "../../src/bin/recognize.py", line 69, in <module>
        recognize(args)
    File "../../src/bin/recognize.py", line 58, in recognize
        nbest_hyps = model.recognize(input, input_length, char_list, args)
    File "/home/tt/Speech-Transformer/src/transformer/transformer.py", line 46, in recognize
        args)
    File "/home/tt/Speech-Transformer/src/transformer/decode.py", line 222, in recognize_beam
        for x in hyp['yes'][0, 1:]]))
UnicodeEncodeError: 'ascii' codec can't encode character '\u751a' in position 6: ordinal not in range(128)
```
Any solution?

**Comment by neulqz** [comment]
I got the same error when i run script  "run.sh",then I solve it by adding the following in run.sh ,hope it can help you .

export PYTHONIOENCODING=utf-8
if [ ${stage} -le 4 ]; then
    echo "stage 4: Decoding"
    ......

**Comment by alexlfyang** [comment]
@neulqz Yes, it works. Thx.
